### PR TITLE
fix: issue #33 postman request descriptions are strings

### PR DESCRIPTION
**Pull request by YOU54F**

### CODE REVIEW

**Comment by frankkilcommins** [comment]
A collection description has a `oneOf` structure based on the following schema:

```json

   "description":{
      "$schema":"http://json-schema.org/draft-07/schema#",
      "$id":"#/definitions/description",
      "description":"A Description can be a raw text, or be an object, which holds the description along with its format.",
      "oneOf":[
         {
            "type":"object",
            "title":"Description",
            "properties":{
               "content":{
                  "type":"string",
                  "description":"The content of the description goes here, as a raw string."
               },
               "type":{
                  "type":"string",
                  "description":"Holds the mime type of the raw description content. E.g: 'text/markdown' or 'text/html'.\nThe type is used to correctly render the description when generating documentation, or in the Postman app."
               },
               "version":{
                  "description":"Description can have versions associated with it, which should be put in this property."
               }
            }
         },
         {
            "type":"string"
         },
         {
            "type":"null"
         }
      ]
   }

```

We should deal with the possible options

**Comment by YOU54F** [comment]
I don't believe we are using the parsed value anyway, so we could remove it from attempting to parse completely

Do we have anywhere we can use the description in explore?

If we did, we would want to consider what we can support. Will wherever the field is displayed, does it need truncating? can it support alternate content types? do we want to?

**Comment by frankkilcommins** [comment]
It might depend on if we continue using the flat structure or if we allow nesting (preferred) and have multiple request per API "folder".

We could use the API "description" like at:
https://github.com/SmartBear-DevRel/explore-cli/blob/main/src/Explore.Cli/Program.cs#L385

**Comment by YOU54F** [comment]
> We could use the API "description" like at:

good suggestion, implemented

> We should deal with the possible options

done, `Description.Content`, will now contain the value of `description` if it is a json string, otherwise it will be set to `description.content` if it exists.

`Description.Type` / `Description.Version` may also exist, and `Description` may be `null`

The `Description.Content` value is now used for the description of each uploaded item, and viewable from the UI. I've newline separated the time stamp below

**Review by frankkilcommins — APPROVED** [review]
LGTM - thanks @YOU54F

**Pull request merged**
